name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

env:
  VOLTA_FEATURE_PNPM: 1

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: volta-cli/action@v4.2.1
      - uses: actions/cache@v6.0.0
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Persist Eleventy .cache
        uses: actions/cache@v6.0.0
        with:
          path: ./.cache
          key: ${{ runner.os }}-eleventy-fetch-cache
      - run: pnpm install
      - run: pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
